### ISSUE TITLE
Back and forward buttons

### ISSUE THREAD

**Issue by lastmjs** [electrovir/Matrix_Operator#4]
It would be really nice to go back one operation, and then move forward one operation. Right now if I make a mistake I potentially have to start over. Shouldn't be too hard if you use REDUX

**Comment by mwilliammyers** [comment]
Love the app! That would make this even better!

**Comment by electrovir** [comment]
Thanks for the input!

I'm currently working on it.

**Comment by electrovir** [comment]
This has now been implemented!
